### ISSUE TITLE
Why do I keep being reminded that there is another instance of the game?为什么我一直被提醒有另一个游戏进程

### ISSUE THREAD

**Issue by leez3sun** [34736384/genshin-fps-unlock#309]
I did not open the game program, restart the computer still so (already running as an administrator)
我并没有打开游戏程序，重启电脑仍然如此（已经以管理员身份运行）
![0671c5d54ac892479ecfd72915abb57c](https://github.com/34736384/genshin-fps-unlock/assets/154106649/3b89c655-1c35-49e7-a775-5fb7d5c634a4)

**Comment by cu3198** [comment]
The same is true in version 2.2,
while v3.0.2 doesn't work,it popups an err msg "System.ComponentModel.Win32Exception: Access is denied"
```
   System.ComponentModel.Win32Exception (5): Access is denied。
   at System.Diagnostics.Process.Kill()
   at unlockfps_nc.Service.ProcessService.<>c.<Start>b__14_1(Process x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at unlockfps_nc.Service.ProcessService.Start()
   at unlockfps_nc.MainForm.BtnStartGame_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

**Comment by CrooLyyCheck** [comment]
Its annoying for me, i use two windows users at same time with rdp and i must launch one instance from normal client, not thru unlocker

**Comment by 34736384** [comment]
will check

**Comment by cu3198** [comment]
im sry,upon inspecting the task manager,i noticed that when i ended the game, its process was susbended.the suspended status persisting for a few days might have resulted from an abnormal closure.
both 2 versions worked fine after killed the suspended process
